<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P92S73M" ignored="0" name="t2" tests="5" failures="2" timestamp="2020-11-15T15:42:41 CST" time="0.049" errors="0">
  <testcase name="test1" time="0.009" classname="com.webtest.demo.FreemarkerTest"/>
  <testcase name="test2" time="0.001" classname="com.webtest.demo.FreemarkerTest"/>
  <testcase name="test3" time="0.001" classname="com.webtest.demo.FreemarkerTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.FreemarkerTest.test3(FreemarkerTest.java:28)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="com.webtest.demo.FreemarkerTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.demo.FreemarkerTest.test4(FreemarkerTest.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.001" classname="com.webtest.demo.FreemarkerTest"/>
</testsuite> <!-- t2 -->
